### ISSUE TITLE
Fill text layer per the order defined in the JSON file

### ISSUE THREAD

**Issue by myhandleisdan** [TDMW/figma-json-populate#1]
Hey man, love the plugin!

I was wondering if it'd it be possible to fill the text layer(s) as per the order of the values defined in the JSON object? Right now, when I click on a button, i.e., Cities, it fills my text layer(s) using a random value from the object. 

My use case is that I'd like to import a JSON file containing all my icon names (ordered alphabetically). Doing so would allow me to import all my icons into text layers using a font file in a single click. (I assume it would repeat upon reaching the end of the list if I have more text layers than entries in my JSON file to prevent errors.)

Let me know if that's something you'd like to implement in the future. I'd be more than happy to contribute.

**Comment by A7DC** [comment]
+1 for this feature. Using custom JSON (at least for my purposes) is only feasible if the order of entries is respected. :(

**Comment by A7DC** [comment]
Hey @TDMW I have created a PR for this feature. It's my first PR in open source, so any feedback is welcome, hopefully I've done it correctly! https://github.com/TDMW/figma-json-populate/pull/2

**Comment by TDMW** [comment]
I've just released a update that accomodates filling randomly and filling using the original intended order of the JSON! For now I'll be closing this issue.

**Comment by stephenmeszaros** [comment]
Thanks for this plugin! I'm testing it out and it seems like original ordering is not respected. Is there something I'm doing incorrectly? Code example and screenshot from Figma below. I am selecting "Fill order: Original" via the Figma plugin UI.

```
{
"Timestamp": [
      "29 Aug 2020 23:57:58",
      "29 Aug 2020 22:34:14",
      "29 Aug 2020 10:01:05",
      "29 Aug 2020 06:52:18",
      "29 Aug 2020 02:53:01",
      "28 Aug 2020 23:50:25",
      "28 Aug 2020 20:30:44",
      "28 Aug 2020 19:25:31",
      "28 Aug 2020 15:11:01",
      "26 Aug 2020 16:33:58"
    ]
}
```

Results in
<img width="275" alt="CleanShot 2020-08-18 at 12 02 31@2x" src="https://user-images.githubusercontent.com/5034518/90548810-bfce0180-e14a-11ea-9334-fabf3c35a660.png">

Thanks for any help!
