### ISSUE TITLE
Real-time update?

### ISSUE THREAD

**Issue by mgalavai** [TDMW/figma-json-populate#5]
Hi! Thanks for the plugin, really useful!
One suggestion if I may, I wonder if it's possible at all...
How about automatic update the text box in Figma, when the source changed?
Think of a weather temperature for example. Or any other 3rd party source of data.

Thanks

**Comment by TDMW** [comment]
I think this would be possible in some capacity, but would also make the plugin way more complex. I'd have to keep track of what piece of the JSON is used on which text layer (if I get your comment right) so I can update it if the source JSON has changed. While I do understand the need, I don't foresee me implementing this in the close future.

**Comment by mgalavai** [comment]
I see. Ok, thanks for the answer 👍
